"""Hallucination Risk Classifier — binary classification (faithful vs hallucinated).

The clever bit (systems thinking interviewers like): training labels are
generated by *weak supervision* from RAGAS faithfulness scores. RAGAS (an
LLM-as-judge) is expensive and needs an API call per answer; we use it once,
offline, to label a training set, then distil that signal into a fast local
logistic-regression model that scores groundedness from cheap features at
inference time — no API call in the hot path.

  faithfulness >= tau  -> label 1 (faithful)
  faithfulness <  tau   -> label 0 (hallucinated)

Reported metric: ROC-AUC on a held-out split.
"""
from __future__ import annotations

import json
import pickle
from pathlib import Path
from typing import Dict, List

import numpy as np

from ..config import CFG
from .features import extract

MODEL_PATH = Path(CFG["paths"]["models_dir"]) / "halluc_clf.pkl"


class HallucinationClassifier:
    def __init__(self) -> None:
        self.clf = None
        self.scaler = None

    # -------------------------------------------------------------- training
    def train(self, X: np.ndarray, y: List[int]):
        from sklearn.linear_model import LogisticRegression
        from sklearn.preprocessing import StandardScaler

        self.scaler = StandardScaler().fit(X)
        Xs = self.scaler.transform(X)
        self.clf = LogisticRegression(max_iter=1000, class_weight="balanced")
        self.clf.fit(Xs, y)
        return self

    def evaluate(self, X: np.ndarray, y: List[int]) -> Dict:
        from sklearn.metrics import roc_auc_score, f1_score
        # y: 1 = faithful (positive class). AUC is measured against P(faithful).
        p_faithful = 1.0 - self.predict_proba_matrix(X)
        try:
            auc = roc_auc_score(y, p_faithful)
        except ValueError:
            auc = float("nan")
        pred = (p_faithful >= 0.5).astype(int)
        return {"auc": float(auc),
                "f1": float(f1_score(y, pred, zero_division=0))}

    # --------------------------------------------------------------- predict
    def predict_proba_matrix(self, X: np.ndarray) -> np.ndarray:
        Xs = self.scaler.transform(X)
        # P(hallucinated) = 1 - P(faithful)
        return 1.0 - self.clf.predict_proba(Xs)[:, list(self.clf.classes_).index(1)]

    def risk(self, answer: str, contexts: List[str]) -> float:
        """Return P(hallucinated) in [0,1]. Falls back to a cosine heuristic."""
        feats = extract(answer, contexts).reshape(1, -1)
        if self.clf is None or self.scaler is None:
            max_cos = feats[0][0]
            return float(max(0.0, 1.0 - max_cos))  # low support -> high risk
        return float(self.predict_proba_matrix(feats)[0])

    # ------------------------------------------------------------------- io
    def save(self) -> None:
        MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(MODEL_PATH, "wb") as f:
            pickle.dump({"clf": self.clf, "scaler": self.scaler}, f)

    def load(self) -> "HallucinationClassifier":
        if MODEL_PATH.exists():
            try:
                with open(MODEL_PATH, "rb") as f:
                    blob = pickle.load(f)
                self.clf, self.scaler = blob["clf"], blob["scaler"]
            except Exception:
                self.clf = self.scaler = None
        return self


_CLF: HallucinationClassifier | None = None


def get_hallucination_classifier() -> HallucinationClassifier:
    global _CLF
    if _CLF is None:
        _CLF = HallucinationClassifier().load()
    return _CLF
